In [42]:
import numpy as np

In [12]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [13]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [14]:
a1-a2

array([-5, -5, -5, -5, -5])

In [16]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [17]:
a1//a2

array([0, 0, 0, 0, 0])

In [33]:
l=[10,20,30,40,50]
arr=np.array(l)

In [34]:
arr=arr+10
arr

array([20, 30, 40, 50, 60])

In [40]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])