In [5]:
import numpy as np

In [7]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [13]:
a=[5,6,7.5,8]
a

[5, 6, 7.5, 8]

In [14]:
np.array(a)

array([5. , 6. , 7.5, 8. ])

In [15]:
l=[[1,2,3],[5,4,6],[9,3,8]]
l

[[1, 2, 3], [5, 4, 6], [9, 3, 8]]

In [16]:
np.array(l)

array([[1, 2, 3],
       [5, 4, 6],
       [9, 3, 8]])

In [20]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr=np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
arr=np.ones(1)
arr

array([1.])

In [26]:
arr=np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
arr=np.linspace(1,3,4)
arr

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [36]:
arr=np.random.rand(5)
arr

array([0.22887042, 0.96691411, 0.87075904, 0.39613823, 0.09803717])

In [41]:
arr=np.random.randn(10)
arr

array([ 0.0463781 , -1.45928307,  0.57114555,  0.15860621,  1.08269924,
        2.30645901, -1.09970903,  0.46081962,  0.77939679,  0.13123179])

In [46]:
arr=np.random.randint(10,20,10)
arr

array([19, 11, 14, 19, 15, 15, 12, 16, 12, 16], dtype=int32)

In [54]:
arr=np.array([[1,2,3],[4,5,2],[4,7,9]])
arr

array([[1, 2, 3],
       [4, 5, 2],
       [4, 7, 9]])

In [55]:
arr.shape

(3, 3)

In [56]:
arr.size

9

In [57]:
arr.dtype

dtype('int64')

In [58]:
arr.min()

np.int64(1)

In [59]:
arr.max()

np.int64(9)

In [60]:
arr.sum()

np.int64(37)

In [62]:
np.sum(arr,axis=0)

array([ 9, 14, 14])

In [63]:
np.sum(arr,axis=1)

array([ 6, 11, 20])

In [64]:
arr.mean()

np.float64(4.111111111111111)

In [65]:
arr.std()

np.float64(2.4241582476968255)

In [66]:
arr.argmax()

np.int64(8)

In [67]:
arr.argmin()

np.int64(0)

In [68]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [69]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [70]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [72]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [73]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [76]:
arr[2]

array([11, 12, 13, 14, 15])

In [78]:
slice=arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [80]:
arr[:,2]


array([ 3,  8, 13, 18, 23, 28])